# API router package

from app.routers import (  # noqa: F401
    auth_routes,
    store_routes,
    employee_routes,
    product_routes,
    order_routes,
    kot_routes,
    analytics_routes,
    menu_routes,
    inventory_routes,
    purchasing_routes,
    delivery_routes,
    shift_routes,
    billing_routes,
    guest_routes,
    ledger_routes,
    integration_routes,
    marketing_routes,
    audit_routes,
    user_routes,
    chain_routes,
    group_routes,
    notification_routes,
    zone_routes,
    report_routes,
    terminal_routes,
    expense_routes,
    kitchen_routes,
)
