"""add pin to employee

Revision ID: 4d38122b7292
Revises: a6082c99aeb2
Create Date: 2026-03-16 07:23:31.618224
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d38122b7292'
down_revision: Union[str, None] = 'a6082c99aeb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'pin_hash', new_column_name='pin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'pin', new_column_name='pin_hash')
    # ### end Alembic commands ###
