"""extend_platform_full_features

Revision ID: f29df2f97962
Revises: 8b5187e1f4f2
Create Date: 2026-03-07 20:45:08.432387
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f29df2f97962'
down_revision: Union[str, None] = '8b5187e1f4f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dine_in_tables', sa.Column('label', sa.String(length=50), nullable=True))
    op.add_column('dine_in_tables', sa.Column('section', sa.String(length=50), nullable=True))
    op.add_column('dine_in_tables', sa.Column('zone', sa.String(length=50), nullable=True))
    op.add_column('dine_in_tables', sa.Column('position_x', sa.Integer(), nullable=True))
    op.add_column('dine_in_tables', sa.Column('position_y', sa.Integer(), nullable=True))
    op.add_column('dine_in_tables', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('dine_in_tables', sa.Column('current_order_id', sa.UUID(), nullable=True))
    op.create_index('ix_dine_in_tables_status', 'dine_in_tables', ['status'], unique=False)
    op.add_column('employees', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('employees', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('employees', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('employees', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('employees', sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('employees', 'pin',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_index('ix_employees_user_id', 'employees', ['user_id'], unique=False)
    op.create_foreign_key(None, 'employees', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('expenses', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('expenses', sa.Column('shift_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'expenses', 'shifts', ['shift_id'], ['id'], ondelete='SET NULL')
    op.add_column('order_items', sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False, server_default=sa.text('0')))
    op.add_column('order_items', sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False, server_default=sa.text('0')))
    op.add_column('order_items', sa.Column('status', sa.String(length=20), nullable=False, server_default=sa.text("'active'")))
    op.add_column('order_items', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('order_items', sa.Column('cancel_reason', sa.String(length=255), nullable=True))
    op.add_column('order_items', sa.Column('kot_id', sa.UUID(), nullable=True))
    op.add_column('order_items', sa.Column('kitchen_status', sa.String(length=20), nullable=True))
    op.create_index('ix_order_items_status', 'order_items', ['status'], unique=False)
    op.create_foreign_key(None, 'order_items', 'kots', ['kot_id'], ['id'], ondelete='SET NULL')
    op.add_column('orders', sa.Column('guest_id', sa.UUID(), nullable=True))
    op.add_column('orders', sa.Column('shift_id', sa.UUID(), nullable=True))
    op.add_column('orders', sa.Column('order_number', sa.String(length=30), nullable=True))
    op.add_column('orders', sa.Column('status', sa.String(length=20), nullable=False, server_default=sa.text("'new'")))
    op.add_column('orders', sa.Column('channel', sa.String(length=20), nullable=False, server_default=sa.text("'dine_in'")))
    op.add_column('orders', sa.Column('service_charge', sa.Numeric(precision=12, scale=2), nullable=False, server_default=sa.text('0')))
    op.add_column('orders', sa.Column('tip_amount', sa.Numeric(precision=12, scale=2), nullable=False, server_default=sa.text('0')))
    op.add_column('orders', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('cancel_reason', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('cancelled_by', sa.UUID(), nullable=True))
    op.add_column('orders', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('ledger_account_id', sa.UUID(), nullable=True))
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.create_index('ix_orders_guest_id', 'orders', ['guest_id'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_index('ix_orders_store_date', 'orders', ['store_id', 'created_at'], unique=False)
    op.create_foreign_key(None, 'orders', 'guests', ['guest_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'orders', 'shifts', ['shift_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'orders', 'city_ledger_accounts', ['ledger_account_id'], ['id'], ondelete='SET NULL')
    op.add_column('payments', sa.Column('tip_amount', sa.Numeric(precision=12, scale=2), nullable=False, server_default=sa.text('0')))
    op.add_column('payments', sa.Column('reference', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('is_refund', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('payments', sa.Column('original_payment_id', sa.UUID(), nullable=True))
    op.alter_column('payments', 'payment_method',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.create_index('ix_payments_method', 'payments', ['payment_method'], unique=False)
    op.create_foreign_key(None, 'payments', 'payments', ['original_payment_id'], ['id'], ondelete='SET NULL')
    op.add_column('pos_terminals', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('stores', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('stores', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('stores', sa.Column('timezone', sa.String(length=64), nullable=False, server_default=sa.text("'UTC'")))
    op.add_column('stores', sa.Column('currency', sa.String(length=3), nullable=False, server_default=sa.text("'INR'")))
    op.add_column('stores', sa.Column('tax_inclusive', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('stores', sa.Column('chain_id', sa.UUID(), nullable=True))
    op.add_column('stores', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.create_index('ix_stores_chain_id', 'stores', ['chain_id'], unique=False)
    op.create_foreign_key(None, 'stores', 'chains', ['chain_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=False, server_default=sa.text("'owner'")))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.drop_index('ix_stores_chain_id', table_name='stores')
    op.drop_column('stores', 'is_active')
    op.drop_column('stores', 'chain_id')
    op.drop_column('stores', 'tax_inclusive')
    op.drop_column('stores', 'currency')
    op.drop_column('stores', 'timezone')
    op.drop_column('stores', 'email')
    op.drop_column('stores', 'phone')
    op.drop_column('pos_terminals', 'is_active')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index('ix_payments_method', table_name='payments')
    op.alter_column('payments', 'payment_method',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('payments', 'original_payment_id')
    op.drop_column('payments', 'is_refund')
    op.drop_column('payments', 'reference')
    op.drop_column('payments', 'tip_amount')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index('ix_orders_store_date', table_name='orders')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index('ix_orders_guest_id', table_name='orders')
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'ledger_account_id')
    op.drop_column('orders', 'cancelled_at')
    op.drop_column('orders', 'cancelled_by')
    op.drop_column('orders', 'cancel_reason')
    op.drop_column('orders', 'notes')
    op.drop_column('orders', 'tip_amount')
    op.drop_column('orders', 'service_charge')
    op.drop_column('orders', 'channel')
    op.drop_column('orders', 'status')
    op.drop_column('orders', 'order_number')
    op.drop_column('orders', 'shift_id')
    op.drop_column('orders', 'guest_id')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_index('ix_order_items_status', table_name='order_items')
    op.drop_column('order_items', 'kitchen_status')
    op.drop_column('order_items', 'kot_id')
    op.drop_column('order_items', 'cancel_reason')
    op.drop_column('order_items', 'notes')
    op.drop_column('order_items', 'status')
    op.drop_column('order_items', 'discount_amount')
    op.drop_column('order_items', 'tax_amount')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'shift_id')
    op.drop_column('expenses', 'notes')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_index('ix_employees_user_id', table_name='employees')
    op.alter_column('employees', 'pin',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('employees', 'permissions')
    op.drop_column('employees', 'is_active')
    op.drop_column('employees', 'email')
    op.drop_column('employees', 'phone')
    op.drop_column('employees', 'user_id')
    op.drop_index('ix_dine_in_tables_status', table_name='dine_in_tables')
    op.drop_column('dine_in_tables', 'current_order_id')
    op.drop_column('dine_in_tables', 'is_active')
    op.drop_column('dine_in_tables', 'position_y')
    op.drop_column('dine_in_tables', 'position_x')
    op.drop_column('dine_in_tables', 'zone')
    op.drop_column('dine_in_tables', 'section')
    op.drop_column('dine_in_tables', 'label')
    # ### end Alembic commands ###
